mapname = 'Internet Explorer 6';

modes = ['Default',];

keys['Default']=[
'PgUp	PgUp	Scroll toward the beginning of a document in larger increments',
'Ctrl+W	Close	Close the current window',
'Esc	Stop	Stop downloading a page',
'End	End	Move to the end of a document',
'Ctrl+L	Open	Go to a new location',
'Shift+ 	Scrollup	Scrolls up a bit.',
' 	Scroll	Scrolls down a bit.',
'Ctrl+B	FavOrg	Open the Organize Favorites dialog box',
'Ctrl+E	Search	Open the Search bar',
'Ctrl+D	FavAdd	Add the current page to your favorites',
'Alt+D	Url	Select the text in the Address bar',
'Ctrl+F	Find	Find on this page',
'Ctrl+I	Favs	Open the Favorites bar',
'Ctrl+H	History	Open the History bar',
'Alt+Up	FavUp	Move selected item up in the Favorites list in the Organize Favorites dialog box',
'Up	ScrUp	Scroll toward the beginning of a document',
'Ctrl+O	Open	Go to a new location',
'Ctrl+N	New	Open a new window',
'Ctrl+P	Print	Print the current page or active frame',
'Ctrl+S	Save	Save the current page',
'Ctrl+R	Refresh	Refresh the current Web page',
'Shift+Bkspce	Forward	Go to the next page',
'Bkspce	Back	Go to the previous page',
'Ctrl+Enter	UrlAuto	Add "www and .com',
'Shift+F10	Shortcut	Display a shortcut menu for a link',
'F11	Full-screen	Toggle between full-screen and regular views of the browser window',
'Ctrl+Left	UrlLeft	When in the Address bar, move the cursor left to the next logical break in the address (period or slash)',
'Alt+Left	Back	Go to the previous page',
'F1	Help	Display Internet Explorer Help, or when in a dialog box, display context Help on an item',
'Ctrl+Right	UrlRight	When in the Address bar, move the cursor right to the next logical break in the address (period or slash)',
'Alt+Right	Forward	Go to the next page',
'F4	Dropdown	Display a list of addresses you\'ve typed',
'Ctrl+F5	ForceRefresh	Refresh the current Web page, even if the time stamp for the Web version and your locally stored version are the same',
'F5	Refresh	Refresh the current Web page',
'F6	Url	Move forward between frames',
'PgDn	PgDn	Scroll toward the end of a document in larger increments',
'Alt+Down	FavDown	Move selected item down in the Favorites list in the Organize Favorites dialog box',
'Down	ScrDn	Scroll toward the end of a document',
'Ctrl+Tab	Url	Move forward between frames',
'Shift+Tab	Backtab	Move back through the items on a Web page, the Address bar, and the Links bar',
'Ctrl+Shift+Tab	Frame	Move back between frames',
'Tab	Tab	Move forward through the items on a Web page, the Address bar, and the Links bar',
'Alt+Home	Home	Go to your Home page',
'Home	Top	Move to the beginning of a document',
];

