mapname = 'visual studio 2003';

modes = ['Global','Text Editor','Class Diagram','DataSet Editor','Deployment Designer','HTML Editor Design View','HTML Editor Source View','Managed Resources Editor','Report Designer','Settings Designer','VC Accelerator Editor','VC Dialog Editor','VC Image Editor','VC String Editor','View Designer','WebBrowser','Windows Forms Designer','XML Editor Schema View',];

keys['Global']=[
'Shift+Up	Edit.SizeControlUpGrid||SizeControlUpGrid	',
'Shift+Right	Edit.SizeControlRightGrid||SizeControlRightGrid	',
'Alt+Right	View.Forward||Forward	',
'Ctrl+Shift+W	File.ViewinBrowser||ViewinBrowser	',
'Ctrl+Alt+V	Debug.Watch#||Watch#	',
'Shift+Esc	Window.CloseToolWindow||CloseToolWindow	',
'Esc	Window.ActivateDocumentWindow||ActivateDocumentWindow	',
'Ctrl+Shift+1	View.BrowseNext||BrowseNext	',
'Ctrl+Shift+Z	Edit.Redo||Redo	',
'Ctrl+Alt+Z	Debug.Processes||Processes	',
'Ctrl+-	View.NavigateBackward||NavigateBackward	',
'Ctrl+Shift+-	View.NavigateForward||NavigateForward	',
'Ctrl+/	Tools.GoToCommandLine||GoToCommandLine	',
'Ctrl+.	View.ShowSmartTag||ShowSmartTag	',
'Ctrl+Break	Build.Cancel||Cancel	',
'Ctrl+Alt+Break	Debug.BreakAll||BreakAll	',
'Ctrl+Shift+2	View.BrowsePrevious||BrowsePrevious	',
'Ctrl+Shift+7	View.ForwardBrowseContext||ForwardBrowseContext	',
'Ctrl+Shift+8	View.PopBrowseContext||PopBrowseContext	',
'Ctrl+A	Edit.SelectAll||SelectAll	',
'Ctrl+Shift+A	Project.AddNewItem||AddNewItem	',
'Alt+Shift+A	Project.AddExistingItem||AddExistingItem	',
'Ctrl+Alt+A	View.CommandWindow||CommandWindow	',
'Ctrl+Shift+C	View.ClassView||ClassView	',
'Ctrl+Alt+C	Debug.CallStack||CallStack	',
'Ctrl+B	Debug.BreakatFunction||BreakatFunction	',
'Ctrl+Shift+B	Build.BuildSolution||BuildSolution	',
'Ctrl+Alt+B	Debug.Breakpoints||Breakpoints	',
'Ctrl+Shift+E	View.ResourceView||ResourceView	',
'Ctrl+Alt+E	Debug.Exceptions||Exceptions	',
'Ctrl+D	Edit.GoToFindCombo||GoToFindCombo	',
'Alt+Shift+D	Data.ShowDataSources||ShowDataSources	',
'Ctrl+Alt+D	Debug.Disassembly||Disassembly	',
'Ctrl+G	Edit.GoTo||GoTo	',
'Ctrl+Shift+G	Edit.OpenFile||OpenFile	',
'Ctrl+Alt+G	Debug.Registers||Registers	',
'Ctrl+F	Edit.Find||Find	',
'Ctrl+Shift+F	Edit.FindinFiles||FindinFiles	',
'Ctrl+Alt+I	Debug.Immediate||Immediate	',
'Ctrl+H	Edit.Replace||Replace	',
'Ctrl+Shift+H	Edit.ReplaceinFiles||ReplaceinFiles	',
'Ctrl+Alt+H	Debug.Threads||Threads	',
'Ctrl+K	Tools.SnippetsBookmark#||SnippetsBookmark#	',
'Ctrl+Alt+J	View.ObjectBrowser||ObjectBrowser	',
'Ctrl+Alt+M	Debug.Memory#||Memory#	',
'Ctrl+Alt+L	View.SolutionExplorer||SolutionExplorer	',
'Ctrl+O	File.OpenFile||OpenFile	',
'Ctrl+Shift+O	File.OpenProject||OpenProject	',
'Ctrl+Alt+O	View.Output||Output	',
'Ctrl+N	File.NewFile||NewFile	',
'Ctrl+Shift+N	File.NewProject||NewProject	',
'Ctrl+Alt+N	Debug.ScriptExplorer||ScriptExplorer	',
'Ctrl+Q	Data.RunSelection||RunSelection	',
'Ctrl+P	File.Print||Print	',
'Ctrl+Shift+P	Tools.RunTemporaryMacro||RunTemporaryMacro	',
'Ctrl+Alt+P	Tools.AttachtoProcess||AttachtoProcess	',
'Ctrl+S	File.SaveSelectedItems||SaveSelectedItems	',
'Ctrl+Shift+S	File.SaveAll||SaveAll	',
'Ctrl+Alt+S	View.ServerExplorer||ServerExplorer	',
'Ctrl+R	Refactor.Refactor#||Refactor#	',
'Ctrl+Shift+R	Tools.RecordTemporaryMacro||RecordTemporaryMacro	',
'Ctrl+Alt+R	View.WebBrowser||WebBrowser	',
'Shift+Del	Edit.Cut||Cut	',
'Ctrl+Alt+T	View.DocumentOutline||DocumentOutline	',
'Alt+Bkspce	Edit.Undo||Undo	',
'Alt+Enter	Diagram.Properties||Properties	',
'Alt+Shift+Enter	View.FullScreen||FullScreen	',
'Enter	Edit.ShowTileGrid||ShowTileGrid	',
'Ctrl+F12	Edit.GoToDeclaration||GoToDeclaration	',
'Ctrl+Shift+F12	View.NextError||NextError	',
'F12	Edit.GoToDefinition||GoToDefinition	',
'Shift+F12	Edit.FindAllReferences||FindAllReferences	',
'Ctrl+Alt+F12	View.FindSymbolResults||FindSymbolResults	',
'Alt+Shift+F12	Edit.QuickFindSymbol||QuickFindSymbol	',
'Alt+F12	Edit.FindSymbol||FindSymbol	',
'Ctrl+Shift+X	Test.StartSelectedTestProjectwithoutDebugger||StartSelectedTestProjectwithoutDebugger	',
'Alt+Shift+X	Test.StartSelectedTestProjectwithDebugger||StartSelectedTestProjectwithDebugger	',
'Ctrl+Alt+X	View.Toolbox||Toolbox	',
'Ctrl+F10	Debug.RunToCursor||RunToCursor	',
'Ctrl+Shift+F10	Debug.SetNextStatement||SetNextStatement	',
'Alt+F10	Debug.ApplyCodeChanges||ApplyCodeChanges	',
'Ctrl+Alt+F10	Debug.StepOverCurrentProcess||StepOverCurrentProcess	',
'F10	Debug.StepOver||StepOver	',
'Ctrl+F11	Debug.ToggleDisassembly||ToggleDisassembly	',
'Ctrl+Alt+Shift+F11	Debug.StepOutCurrentProcess||StepOutCurrentProcess	',
'F11	Debug.StepInto||StepInto	',
'Shift+F11	Debug.StepOut||StepOut	',
'Ctrl+Alt+F11	Debug.StepIntoCurrentProcess||StepIntoCurrentProcess	',
'Alt+F11	Tools.MacrosIDE||MacrosIDE	',
'Ctrl+\\	View.ErrorList#||ErrorList#	',
'Shift+Left	Edit.SizeControlLeftGrid||SizeControlLeftGrid	',
'Alt+Left	View.Backward||Backward	',
'Ctrl+F1	Help.HowDoI||HowDoI	',
'Shift+F1	Help.WindowHelp||WindowHelp	',
'Ctrl+Alt+F1	Help.Contents||Contents	',
'F1	Help.F1Help||F1Help	',
'Ctrl+F2	Window.MovetoNavigationBar||MovetoNavigationBar	',
'Ctrl+Alt+F2	Help.Index||Index	',
'F2	View.EditLabel||EditLabel	',
'Ctrl+F3	Edit.FindNextSelected||FindNextSelected	',
'Ctrl+Shift+F3	Edit.FindPreviousSelected||FindPreviousSelected	',
'F3	Edit.FindNext||FindNext	',
'Shift+F3	Edit.FindPrevious||FindPrevious	',
'Ctrl+Alt+F3	Help.Search||Search	',
'Alt+Shift+F3	Help.SearchResults||SearchResults	',
'Alt+F3	Edit.StopSearch#||StopSearch#	',
'Ctrl+F4	Window.CloseDocumentWindow||CloseDocumentWindow	',
'Shift+F4	View.PropertyPages||PropertyPages	',
'F4	View.PropertiesWindow||PropertiesWindow	',
'Ctrl+F5	Debug.StartWithoutDebugging||StartWithoutDebugging	',
'Ctrl+Shift+F5	Debug.Restart||Restart	',
'F5	Debug.Start||Start	',
'Shift+F5	Debug.StopDebugging||StopDebugging	',
'Ctrl+Alt+F5	Data.Execute||Execute	',
'Alt+Shift+F5	Debug.StartWithApplicationVerifier||StartWithApplicationVerifier	',
'Alt+F5	Data.StepInto||StepInto	',
'Ctrl+F6	Window.NextDocumentWindow||NextDocumentWindow	',
'Ctrl+Shift+F6	Window.PreviousDocumentWindow||PreviousDocumentWindow	',
'F6	Window.NextSplitPane||NextSplitPane	',
'Shift+F6	Window.PreviousSplitPane||PreviousSplitPane	',
'Alt+Shift+F6	Window.PreviousPane||PreviousPane	',
'Alt+F6	Window.NextPane||NextPane	',
'Ctrl+F7	Build.Compile||Compile	',
'Alt+F7	Window.NextToolWindowNav||NextToolWindowNav	',
'Alt+Shift+F7	Window.PreviousToolWindowNav||PreviousToolWindowNav	',
'F7	View.ToggleDesigner||ToggleDesigner	',
'Shift+F8	Edit.GoToPrevLocation||GoToPrevLocation	',
'Alt+F8	View.MacroExplorer||MacroExplorer	',
'F8	Edit.GoToNextLocation||GoToNextLocation	',
'Ctrl+F9	Debug.EnableBreakpoint||EnableBreakpoint	',
'Ctrl+Shift+F9	Debug.DeleteAllBreakpoints||DeleteAllBreakpoints	',
'Alt+F9	DebuggerContextMenus.BreakpointsWindow#||BreakpointsWindow#	',
'Shift+F9	Debug.QuickWatch||QuickWatch	',
'F9	Debug.ToggleBreakpoint||ToggleBreakpoint	',
'Ctrl+Ins	Edit.Copy||Copy	',
'Ctrl+Shift+Ins	Edit.CycleClipboardRing||CycleClipboardRing	',
'Ctrl+Alt+Ins	Project.Override||Override	',
'Shift+Ins	Edit.Paste||Paste	',
'Shift+Down	Edit.SizeControlDownGrid||SizeControlDownGrid	',
'Ctrl+Alt+Down	Window.ShowEzMDIFileList||ShowEzMDIFileList	',
'Ctrl+Tab	Window.NextDocumentWindowNav||NextDocumentWindowNav	',
'Ctrl+Shift+Tab	Window.PreviousDocumentWindowNav||PreviousDocumentWindowNav	',
'Tab	Edit.SelectNextControl||SelectNextControl	',
'Shift+Tab	Edit.SelectPreviousControl||SelectPreviousControl	',
'Ctrl+PgDn	Window.NextTab||NextTab	',
'Ctrl+Alt+U	Debug.Modules||Modules	',
];

keys['Text Editor']=[
'Ctrl+PgUp	Edit.ViewTop||ViewTop	',
'Ctrl+Shift+PgUp	Edit.ViewTopExtend||ViewTopExtend	',
'Shift+PgUp	Edit.PageUpExtend||PageUpExtend	',
'PgUp	Edit.PageUp||PageUp	',
'Ctrl+W	Edit.SelectCurrentWord||SelectCurrentWord	',
'Ctrl+Space	Edit.CompleteWord||CompleteWord	',
'Ctrl+Shift+Space	Edit.ParameterInfo||ParameterInfo	',
'Shift+End	Edit.LineEndExtend||LineEndExtend	',
'Alt+Shift+End	Edit.LineEndExtendColumn||LineEndExtendColumn	',
'End	Edit.LineEnd||LineEnd	',
'Ctrl+U	Edit.MakeLowercase||MakeLowercase	',
'Ctrl+Shift+U	Edit.MakeUppercase||MakeUppercase	',
'Alt+,	Edit.DecreaseFilterLevel||DecreaseFilterLevel	',
'Alt+.	Edit.IncreaseFilterLevel||IncreaseFilterLevel	',
'Ctrl+=	Edit.SelectToLastGoBack||SelectToLastGoBack	',
'Ctrl+Alt+Shift+C	Edit.CopyParameterTip||CopyParameterTip	',
'Ctrl+E	Edit.ToggleWordWrap#||ToggleWordWrap#	',
'Ctrl+I	Edit.IncrementalSearch||IncrementalSearch	',
'Ctrl+Shift+I	Edit.ReverseIncrementalSearch||ReverseIncrementalSearch	',
'Ctrl+K	Edit.Bookmarks#||Bookmarks#	',
'Ctrl+J	Edit.ListMembers||ListMembers	',
'Ctrl+M	Edit.Outlining||Outlining	',
'Ctrl+L	Edit.LineCut||LineCut	',
'Ctrl+Shift+L	Edit.LineDelete||LineDelete	',
'Ctrl+Up	Edit.ScrollLineUp||ScrollLineUp	',
'Alt+Shift+Up	Edit.LineUpExtendColumn||LineUpExtendColumn	',
'Ctrl+Alt+Shift+P	Edit.PasteParameterTip||PasteParameterTip	',
'Ctrl+R	Edit.ViewWhiteSpace#||ViewWhiteSpace#	',
'Ctrl+Del	Edit.WordDeleteToEnd||WordDeleteToEnd	',
'Ctrl+T	Edit.CharTranspose||CharTranspose	',
'Ctrl+Shift+T	Edit.WordTranspose||WordTranspose	',
'Alt+Shift+T	Edit.LineTranspose||LineTranspose	',
'Ctrl+Bkspce	Edit.WordDeleteToStart||WordDeleteToStart	',
'Bkspce	Edit.DeleteBackwards||DeleteBackwards	',
'Ctrl+Enter	Edit.LineOpenAbove||LineOpenAbove	',
'Ctrl+Shift+Enter	Edit.LineOpenBelow||LineOpenBelow	',
'Ctrl+]	Edit.GotoBrace||GotoBrace	',
'Ctrl+Shift+]	Edit.GotoBraceExtend||GotoBraceExtend	',
'Ctrl+Left	Edit.WordPrevious||WordPrevious	',
'Ctrl+Alt+Shift+Left	Edit.WordPreviousExtendColumn||WordPreviousExtendColumn	',
'Alt+Shift+Left	Edit.CharLeftExtendColumn||CharLeftExtendColumn	',
'Ctrl+Shift+Left	Edit.WordPreviousExtend||WordPreviousExtend	',
'Ctrl+Right	Edit.WordNext||WordNext	',
'Ctrl+Alt+Shift+Right	Edit.WordNextExtendColumn||WordNextExtendColumn	',
'Alt+Shift+Right	Edit.CharRightExtendColumn||CharRightExtendColumn	',
'Ctrl+Shift+Right	Edit.WordNextExtend||WordNextExtend	',
'Ctrl+PgDn	Edit.ViewBottom||ViewBottom	',
'Ctrl+Shift+PgDn	Edit.ViewBottomExtend||ViewBottomExtend	',
'Shift+PgDn	Edit.PageDownExtend||PageDownExtend	',
'PgDn	Edit.PageDown||PageDown	',
'Ins	Edit.OvertypeMode||OvertypeMode	',
'Ctrl+Down	Edit.ScrollLineDown||ScrollLineDown	',
'Alt+Shift+Down	Edit.LineDownExtendColumn||LineDownExtendColumn	',
'Shift+Home	Edit.LineStartExtend||LineStartExtend	',
'Alt+Shift+Home	Edit.LineStartExtendColumn||LineStartExtendColumn	',
'Home	Edit.LineStart||LineStart	',
];

keys['Class Diagram']=[
'Alt+Shift+B	Edit.ExpandCollapseBaseTypeList||ExpandCollapseBaseTypeList	',
'Alt+Shift+L	Edit.NavigateToLollipop||NavigateToLollipop	',
'%Num%-	ClassDiagram.Collapse||Collapse	',
'Ctrl+Del	Edit.Delete||Delete	',
'Del	Edit.RemovefromDiagram||RemovefromDiagram	',
'%Num%+	ClassDiagram.Expand||Expand	',
'Enter	View.ViewCode||ViewCode	',
];

keys['DataSet Editor']=[
'Ctrl+L	Data.Column||Column	',
'Ins	Data.InsertColumn||InsertColumn	',
];

keys['Deployment Designer']=[
'Alt+Shift+D	Diagram.RedrawConnection||RedrawConnection	',
'Alt+Shift+T	Diagram.RerouteConnection||RerouteConnection	',
];

keys['HTML Editor Design View']=[
'Ctrl+Q	View.VisibleBorders||VisibleBorders	',
'Ctrl+Shift+Q	View.Details||Details	',
'Ctrl+Alt+Q	View.NonVisualControls||NonVisualControls	',
'Ctrl+B	Format.Bold||Bold	',
'Shift+F7	View.ViewMarkup||ViewMarkup	',
'Ctrl+I	Format.Italic||Italic	',
'Ctrl+M	Project.Content#||Content#	',
'Ctrl+L	Format.ConverttoHyperlink||ConverttoHyperlink	',
'Ctrl+Shift+L	Format.InsertBookmark||InsertBookmark	',
'Ctrl+Alt+Up	Layout.InsertRowAbove||InsertRowAbove	',
'Ctrl+Alt+Down	Layout.InsertRowBelow||InsertRowBelow	',
'Ctrl+Alt+Right	Layout.InsertColumntotheRight||InsertColumntotheRight	',
'Ctrl+U	Format.Underline||Underline	',
'Ctrl+Alt+Left	Layout.InsertColumntotheLeft||InsertColumntotheLeft	',
];

keys['HTML Editor Source View']=[
'Ctrl+PgDn	View.NextView||NextView	',
'Shift+F7	View.ViewDesigner||ViewDesigner	',
'Ctrl+PgUp	Window.PreviousTab||PreviousTab	',
'Ctrl+Shift+.	View.AutoCloseTagOverride||AutoCloseTagOverride	',
];

keys['Managed Resources Editor']=[
'Ctrl+1	Resources.Strings||Strings	',
'Ctrl+3	Resources.Icons||Icons	',
'Ctrl+2	Resources.Images||Images	',
'Ctrl+5	Resources.Files||Files	',
'Ctrl+4	Resources.Audio||Audio	',
'Ctrl+6	Resources.Other||Other	',
'Del	Edit.Remove||Remove	',
];

keys['Report Designer']=[
'Ctrl+Right	Edit.MoveControlRight||MoveControlRight	',
'Ctrl+Shift+Right	Edit.SizeControlRight||SizeControlRight	',
'Shift+Right	Edit.CharRightExtend||CharRightExtend	',
'Right	Edit.CharRight||CharRight	',
'Ctrl+Alt+D	View.Datasets||Datasets	',
'Ctrl+Up	Edit.MoveControlUp||MoveControlUp	',
'Ctrl+Shift+Up	Edit.SizeControlUp||SizeControlUp	',
'Up	Edit.LineUp||LineUp	',
'Shift+Up	Edit.LineUpExtend||LineUpExtend	',
'Ctrl+Down	Edit.MoveControlDown||MoveControlDown	',
'Ctrl+Shift+Down	Edit.SizeControlDown||SizeControlDown	',
'Shift+Down	Edit.LineDownExtend||LineDownExtend	',
'Down	Edit.LineDown||LineDown	',
'Shift+Tab	Edit.TabLeft||TabLeft	',
'Tab	Edit.InsertTab||InsertTab	',
'Enter	Edit.BreakLine||BreakLine	',
'Ctrl+Left	Edit.MoveControlLeft||MoveControlLeft	',
'Ctrl+Shift+Left	Edit.SizeControlLeft||SizeControlLeft	',
'Shift+Left	Edit.CharLeftExtend||CharLeftExtend	',
'Left	Edit.CharLeft||CharLeft	',
];

keys['Settings Designer']=[
'Esc	Edit.SelectionCancel||SelectionCancel	',
'F2	Edit.EditCell||EditCell	',
'Ctrl+Del	Edit.RemoveRow||RemoveRow	',
];

keys['VC Accelerator Editor']=[
'Ctrl+W	Edit.NextKeyTyped||NextKeyTyped	',
'Ins	Edit.NewAccelerator||NewAccelerator	',
];

keys['VC Dialog Editor']=[
'Ctrl+B	Format.ButtonBottom||ButtonBottom	',
'Ctrl+D	Format.TabOrder||TabOrder	',
'Ctrl+G	Format.ToggleGuides||ToggleGuides	',
'Shift+F7	Format.SizetoContent||SizetoContent	',
'Ctrl+F9	Format.CenterVertical||CenterVertical	',
'Ctrl+Shift+F9	Format.CenterHorizontal||CenterHorizontal	',
'Shift+F9	Format.AlignCenters||AlignCenters	',
'F9	Format.AlignMiddles||AlignMiddles	',
'Ctrl+M	Format.CheckMnemonics||CheckMnemonics	',
'Ctrl+Shift+Up	Format.AlignTops||AlignTops	',
'Alt+Up	Format.SpaceDown||SpaceDown	',
'Ctrl+Shift+Down	Format.AlignBottoms||AlignBottoms	',
'Ctrl+R	Format.ButtonRight||ButtonRight	',
'Ctrl+T	Format.TestDialog||TestDialog	',
'Ctrl+Right	Edit.ScrollColumnRight||ScrollColumnRight	',
'Ctrl+Shift+Right	Format.AlignRights||AlignRights	',
'Alt+Right	Format.SpaceAcross||SpaceAcross	',
'Ctrl+Left	Edit.ScrollColumnLeft||ScrollColumnLeft	',
'Ctrl+Shift+Left	Format.AlignLefts||AlignLefts	',
];

keys['VC Image Editor']=[
'Ctrl+A	Image.AirbrushTool||AirbrushTool	',
'Ctrl+M	Image.MagnificationTool||MagnificationTool	',
'Ctrl+Shift+M	Image.Magnify||Magnify	',
'Ctrl+B	Image.BrushTool||BrushTool	',
'Ctrl+F	Image.FillTool||FillTool	',
'Ctrl+I	Image.PencilTool||PencilTool	',
'Ctrl+Shift+I	Image.EraseTool||EraseTool	',
'Ctrl+=	Image.LargerBrush||LargerBrush	',
'Ctrl+J	Image.DrawOpaque||DrawOpaque	',
'Ctrl+-	Image.SmallerBrush||SmallerBrush	',
'Ctrl+Shift+,	Image.ZoomOut||ZoomOut	',
'Ctrl+.	Image.SmallBrush||SmallBrush	',
'Ctrl+Shift+.	Image.ZoomIn||ZoomIn	',
'Ctrl+Alt+Shift+P	Image.FilledEllipseTool||FilledEllipseTool	',
'Alt+P	Image.EllipseTool||EllipseTool	',
'Alt+Shift+P	Image.OutlinedEllipseTool||OutlinedEllipseTool	',
'Ctrl+Alt+Shift+S	Image.ShowTileGrid||ShowTileGrid	',
'Alt+Shift+S	Image.RectangleSelectionTool||RectangleSelectionTool	',
'Ctrl+Alt+S	Image.ShowGrid||ShowGrid	',
'Ctrl+Alt+Shift+R	Image.FilledRectangleTool||FilledRectangleTool	',
'Alt+R	Image.RectangleTool||RectangleTool	',
'Alt+Shift+R	Image.OutlinedRectangleTool||OutlinedRectangleTool	',
'Ctrl+U	Image.UseSelectionasBrush||UseSelectionasBrush	',
'Ctrl+Shift+U	Image.CopyandOutlineSelection||CopyandOutlineSelection	',
'Ctrl+T	Image.TextTool||TextTool	',
'Ctrl+Alt+Shift+W	Image.FilledRoundedRectangleTool||FilledRoundedRectangleTool	',
'Alt+W	Image.RoundedRectangleTool||RoundedRectangleTool	',
'Alt+Shift+W	Image.OutlinedRoundedRectangleTool||OutlinedRoundedRectangleTool	',
'Ctrl+H	Image.FlipHorizontal||FlipHorizontal	',
'Ctrl+Shift+H	Image.Rotate90Degrees||Rotate90Degrees	',
'Alt+Shift+H	Image.FlipVertical||FlipVertical	',
'Ctrl+[	Image.PreviousColor||PreviousColor	',
'Ctrl+Shift+[	Image.PreviousRightColor||PreviousRightColor	',
'Ins	Image.NewImageType||NewImageType	',
'Ctrl+]	Image.NextColor||NextColor	',
'Ctrl+Shift+]	Image.NextRightColor||NextRightColor	',
'Ctrl+L	Image.LineTool||LineTool	',
];

keys['VC String Editor']=[
'Ins	Edit.NewString||NewString	',
];

keys['View Designer']=[
'Ctrl+G	QueryDesigner.GotoRow||GotoRow	',
'Ctrl+Shift+J	QueryDesigner.JoinMode||JoinMode	',
'Ctrl+1	QueryDesigner.Diagram||Diagram	',
'Ctrl+3	QueryDesigner.SQL||SQL	',
'Ctrl+2	QueryDesigner.Criteria||Criteria	',
'Ctrl+4	QueryDesigner.Results||Results	',
'Ctrl+R	QueryDesigner.ExecuteSQL||ExecuteSQL	',
'Ctrl+T	QueryDesigner.CancelRetrievingData||CancelRetrievingData	',
];

keys['WebBrowser']=[
'Alt+Down	Help.Nexttopic||Nexttopic	',
'Alt+Up	Help.Previoustopic||Previoustopic	',
];

keys['Windows Forms Designer']=[
'Shift+Home	Edit.DocumentStartExtend||DocumentStartExtend	',
'Home	Edit.DocumentStart||DocumentStart	',
'Shift+End	Edit.DocumentEndExtend||DocumentEndExtend	',
'End	Edit.DocumentEnd||DocumentEnd	',
];

keys['XML Editor Schema View']=[
'Ctrl+=	Schema.Expand||Expand	',
'Ctrl+-	Schema.Collapse||Collapse	',
];

