mapname = 'Windows XP';

modes = ['Universal','Explorer',];

keys['Universal']=[
'End	Top	Display the bottom of the active window',
'Enter	Ok	Perform the command for the active option or button',
'Alt+PntScr	ScrnShot	Copies a screenshot of the current program to the clipboard',
'PntScr	ScrnShot	Copies a screenshot of the screen to the clipboard',
'Ctrl+Esc	Start	Display the Start menu',
'Ctrl+Shift+Esc	Manager	Task Manager',
'Alt+Esc	Cycle	Cycle through items in the order that they had been opened',
'Alt+ 	Menu	Open the shortcut menu for the active window',
' 	Select	Select or clear the check box if the active option is a check box',
'Win+Break	SysProps	Display the System Properties dialog box ',
'Ctrl+C	Copy 	Copy',
'Win+E	Explorer	Open My Computer ',
'Win+D	Desktop	Display the desktop ',
'Win+F	Search||Ctrl+Win+F Search	Search for computers ',
'Win+M	Restore	Win+Shift+M Restore the minimized windows ',
'Ctrl+Up	ParaUp	Move the insertion point to the beginning of the previous paragraph',
'Win+L	Lock	Lock the keyboard ',
'Win+R	Run	Open the Run dialog box ',
'Win+U	Utility	Open Utility Manager ',
'Ctrl+V	Paste 	Paste',
'Ctrl+X	Cut 	Cut',
'Shift+F10	Rightclick	Display the shortcut menu for the selected item',
'F10	MenuFocus	Activate the menu bar in the active program',
'Ctrl+Z	Undo 	Undo',
'Ctrl+Left	WordLft	Move the insertion point to the beginning of the previous word',
'Win+F1	Help	Display Windows Help ',
'F1	Help	Open Help',
'Ctrl+Right	WordRght	Move the insertion point to the beginning of the next word',
'Ctrl+F4	Close	Close the active document in programs that enable you to have multiple documents open simultaneously',
'Alt+F4	Close	Close Program',
'F4	List	Display the items in the active list',
'Ctrl+Down	ParaDn	Move the insertion point to the beginning of the next paragraph',
'Ctrl+Tab	Tab	Move through tabs',
'Ctrl+Shift+Tab	Tab	Move backward through the tabs ',
'Tab	Focus	Move forward through the options',
'Shift+Tab	Focus	Move backward through the options',
'Alt+Shift+Tab	Switch	Switch backwards between programs',
'Alt+Tab	Switch	Switch between the open items  ',
'Home	End	Display the top of the active window',
];

keys['Explorer']=[
'Ctrl+A	All	Select all',
'F2	Ren	Rename the selected item',
'F3	Search	Search for a file or a folder  ',
'F4	Address	Display the Address bar list in My Computer or Windows Explorer  ',
'F5	Refresh	Update the active window',
'F6	Cycle	Cycle through the screen elements in a window or on the desktop',
'Shift+Del	Del	Delete the selected item permanently without placing the item in the Recycle Bin  ',
'Del	Del	Delete the selected item',
'%Num%+	Collapse	Collapse the selected folder',
'Bkspce	Updir	View the folder one level up in My Computer or Windows Explorer  ',
'Alt+Enter	Props	View the properties for the selected item  ',
'%Num%*	Expand	Display all of the subfolders that are under the selected folder',
'Esc	Cancel	Cancel the current task',
];

