mapname = 'visual studio 2003';

modes = ['Windows Help','Windows Media Player','Calculator, Scientific Mode','Windows Movie Maker','Microsoft Management Console','Remote desktop connection navigation','Character Map',];

keys['Windows Help']=[
'Alt+C	ContentsTab||Contents	 Display the Contents tab.',
'Alt+D	DisplayTab||Display	Display the associated topic.',
'Alt+L	StartSearch||Search	 Start a search.',
'Alt+N	IndexTab||Index	 Display the Index tab.',
'Alt+S	SearchTab||Search	 Display the Search tab.',
'Bkspce	Back	 Return to the previous open book.',
];

keys['Windows Media Player']=[
'Ctrl+1	Full	Full mode',
'Alt+1	View 50%||50%	View 50%',
'Alt+3	View 200%||200%	View 200%',
'Ctrl+2	Skin	Skin mode',
'Alt+2	View 100%||100%	View 100%',
'Ctrl+Shift+C	Caption	Turn on or off captions and subtitles',
'Ctrl+B	Prev	Play previous item CTRL+B ',
'Ctrl+Shift+B	Rewind	Rewind ',
'Ctrl+E	Eject	Eject CD or DVD',
'Ctrl+D	Edit	Edit playlist',
'Ctrl+Shift+G	FasterSpeed||Fast	Play faster than normal speed ',
'Ctrl+F	Next	Play next item ',
'Ctrl+Shift+F	Fastforward||Ffwd	Fast-forward ',
'Ctrl+I	Image	Capture dvd Image',
'Ctrl+H	Shuffle	Shuffle',
'Ctrl+M	ToggleMenubar||Toggle	Toggle menu bar',
'Ctrl+Shift+M	Autohide	Autohide menu',
'Ctrl+O	Open	Open File',
'Ctrl+N	New	New playlist',
'Ctrl+Shift+N	NormalSpeed||Normal	Play at normal speed ',
'Ctrl+P	Play	Play or pause a file',
'Ctrl+S	Stop	Stop playback',
'Ctrl+Shift+S	SlowSpeed||Slow	Play slower than normal speed ',
'Ctrl+U	URL	Open URL',
'Ctrl+T	Loop	Loop playlst',
'Ctrl+W	Close	Close/stop file',
'Alt+Enter	Full	Full screen',
'F10	Vol+	Increase volume  F10',
'F3	Search	Search',
'F8	Mute	Mute volume F8',
'F9	Vol-	Decrease volume  F9',
];

keys['Calculator, Scientific Mode']=[
'V	F-E	Toggle Scientific Notation',
'Y	x^y	x^y',
'Esc	Clr	Clear the Current Calculation',
'%Num%+	+	Add',
'*	*	Multiply',
'-	-	Minus',
'Shift+,	Lsh	Left Shift',
'/	/	Divide',
'.	.	Point',
'Shift+1	n!	Factorial',
'1	Enter 1||1	',
'Shift+0	)	)',
'0	Enter 0||0	',
'Shift+3	x^3	x^3',
'3	Enter 3||3	',
'Shift+2	x^2	x^2',
'2	Enter 2||2	',
'Shift+5	Mod	Modulus',
'5	Enter 5||5	',
'4	Enter 4||4	',
'Shift+7	And	BitwiseAnd',
'7	Enter 7||7	',
'Shift+6	Xor	Bitwise Xor',
'6	Enter 6||6	',
'Shift+9	(	(',
'9	Enter 9||9	',
'8	Enter 8||8	',
';	Int	Truncate Integer',
'Ctrl+A	Ave	Find Mean',
'A	Enter A||A	',
'C	Enter C||C	',
'B	Enter B||B	',
'E	Enter E||E	',
'Ctrl+D	stddev||s	Calculate standard deviation with population parameter of n-1. To use population parameter of n, use Inv+s',
'D	Enter D||D	',
'F	Enter F||F	',
'I	Inv	Sets the inverse function for sin,cos,tan,pi,x^y,x^2,x^3,ln,log,Ave,Sum, and s',
'H	Hyp	Hyperbolic Mode',
'Ctrl+M	MS	Store in Memory',
'M	dms	Convert to degree-minutes-seconds',
'Ctrl+L	MC	Clear Memory',
'L	log	Base 10 log',
'O	cos	cos',
'N	ln	Natural log',
'Ctrl+P	M+	Add to Memory',
'P	pi	pi',
'Ctrl+S	Sta	Activate statistics box',
'S	sin	sin',
'Ctrl+R	MR	Memory Recall',
'R	1/x	Reciprocal',
'Del	CE	Clear the Displayed Number',
'Ctrl+T	Sum	Sum',
'T	tan	tan',
'Bkspce	Del	Backspace',
'Enter	=	Evaluate',
'F12	Qword	Qword',
'X	Exp	Exponentiation',
'Shift+\\	Or	Bitwise or',
'Shift+`	Not	Bitwise not',
'F2	Dword	Dword',
'F3	Word	Word',
'F4	Grads	Grads (400)',
'F5	Hex	Hexadecimal',
'F6	Dec	Decimal',
'F7	Oct	Octal',
'F8	Bin	Binary',
'F9	+/-	Inverse',
'Ins	Dat	Add number to Stat box',
];

keys['Windows Movie Maker']=[
'PgUp	ZoomOut	Zoom out on the timeline',
'Ctrl+V	Paste	Paste',
'F12	Saveas	Save a project as',
' 	Play	Play or pause clip',
'Ctrl+A	SelectAll	Select all clips',
'Ctrl+C	Copy	Copy',
'Ctrl+Shift+B	NudgeLeft||NudgeL	Nudges clip to the left',
'Ctrl+D	Add	Add selected clips to the storyboard/timeline',
'Ctrl+I	Import	Import an existing digital media file',
'Ctrl+Shift+I	TrimStart||Trim	Set start trim point',
'Ctrl+K	Stop	Stop playback on the storyboard/timeline',
'Ctrl+M	Combine	Combine contiguous clips',
'Ctrl+L	Split	Split a clip',
'Ctrl+O	Open	Open an existing project',
'Ctrl+Shift+O	TrimEnd||Trim	Set end trim point',
'Ctrl+N	New	Create a new project',
'Ctrl+Shift+N	NudgeRight||NudgeR	Nudges clip to the right',
'Ctrl+Q	Rewind	Rewind content on the storyboard/timeline',
'Ctrl+P	Export	Save a movie',
'Ctrl+S	Save	Save a project',
'Ctrl+R	Record	Capture video',
'Ctrl+Del	Clear	Clear the storyboard/timeline',
'Ctrl+Shift+Del	TrimClear||ClrTrim	Clear trim points',
'Del	Delete	Delete',
'Ctrl+T	Timeline	Show or hide the storyboard/timeline',
'Ctrl+W	Play	Play content on the storyboard/timeline',
'Alt+Enter	FullScreen	Play video in full screen',
'Ctrl+Y	Redo	Redo the last undone action',
'Ctrl+X	Cut	Cut',
'Ctrl+Z	Undo	Undo the last action',
'Alt+Left	Prev	Previous frame',
'Ctrl+Alt+Left	Back	Back',
'F2	Rename	Rename a collection or clip',
'Alt+Right	Next	Next frame',
'Ctrl+Alt+Right	Forward	Forward',
'PgDn	ZoomIn	Zoom in on the timeline',
];

keys['Microsoft Management Console']=[
'F2	Rename	Rename the selected item',
'Ctrl+F4	Close	Close the active console window. When a console has only one console window, this shortcut closes the console',
'Ctrl+F5	Restore	Restore the active console window',
'F5	Refresh	Update the content of all console windows',
'Ctrl+M	Add	Add or remove a console item',
'Ctrl+O	Open	Open a saved console',
'Ctrl+N	New	Open a new console',
'Ctrl+P	Print	Print the current page or active pane',
'Ctrl+S	Save	Save the open console',
'Alt+%Num%-	Menu	Display the window menu for the active console window',
'Ctrl+W	Window	Open a new window',
'Alt+Enter	Props	Display the Properties dialog box, if any, for the selected item',
'Ctrl+F10	Maximize	Maximize the active console window',
];

keys['Remote desktop connection navigation']=[
'Ctrl+F4	Close	Close the active console window',
'Ctrl+Alt+%Num%.	SnapshotEntire||Snapshot	Place a snapshot of the entire client window area on the Terminal server clipboard and provide the same functionality as pressing ALT+PRINT SCREEN on a local computer.',
'F2	Rename||Ren	Rename the selected item',
'Alt+PgUp	SwitchForward||Switch	Switch between programs from left to right',
'Alt+PgDn	SwitchBack||Switch	Switch between programs from right to left',
'Alt+Ins	Cycle	Cycle through the programs in most recently used order',
'Ctrl+Alt+Break	SwitchClient||Switch	Switch the client computer between a window and a full screen',
'Ctrl+Alt+End	Security	Open the Microsoft Windows NT Security dialog box',
'Alt+Del	Win	Display the Windows menu',
'Ctrl+Alt+%Num%+	SnapshotClient||Snapshot	Place a snapshot of the active window in the client on the Terminal server clipboard and provide the same functionality as pressing PRINT SCREEN on a local computer.',
'Alt+Enter	Props	Display the Properties dialog box, if any, for the selected item',
'Alt+Home	Start	Display the Start menu',
];

keys['Character Map']=[
' 	Enlarge	Switch between Enlarged and Normal mode when a character is selected',
'Right	Right	Move to the right or to the beginning of the next line',
'PgUp	Up	Move up one screen at a time',
'PgDn	Dwn	Move down one screen at a time',
'Up	Up	Move up one row',
'Down	Down	Move down one row',
'Ctrl+End	LastChar	Move to the last character',
'End	End	Move to the end of the line',
'Ctrl+Home	FirstChar	Move to the first character',
'Home	Begin	Move to the beginning of the line',
'Left	Left	Move to the left or to the end of the previous line',
];

