import os

def writeParams(sParam, outFolder):
	if sParam.strip()=='': return True #an empty section means, just all defaults
	#execute it as Python code!
	dlocals = {} #could provide things in here, but won't currently
	code = compile(sParam, '<user-provided code>', 'exec')
	exec code in dlocals
	if 'latest' not in dlocals:
		raise 'Could not find "latest" dictionary.'
	dictLatest = dlocals['latest']
	assert checkADict(dictLatest)
	
	writeADict(dictLatest, os.path.join(outFolder, 'default.cfg'))
	
	#look for animations
	for i in range(1,10):
		sDictName = 'frame0%d'%i 
		if sDictName in dlocals:
			dictFrame = dlocals[sDictName]
			assert checkADict(dictFrame)
			writeADict(dictLatest, os.path.join(outFolder, 'framek0%d.cfg'%i ))
		else:
			#make that frame blank
			ftmp = open(os.path.join(outFolder, 'framek0%d.cfg'%i ), 'w')
			ftmp.write('$')
			ftmp.close()
	

def writeADict(d, filename):
	f = open(filename,'w')
	f.write(';fmmversion=1;')
	for key in d:
		f.write(str(key)+'='+str(d[key])+';')
	f.write('END=0;')
	f.write('\n#Generated by fastpixel, edits to this file will be overwritten.')
	f.write('\n#Fastpixel, Ben Fisher')
	f.close()

def checkADict(d):
	legalKeyNames = '''double pc1;
	double pc2;
	double pc3;
	double pc4;
	double pc5;
	double pc6;
	double pc1b;
	double pc2b;
	double pc3b;
	double pc4b;
	double pc5b;
	double pc6b;
	double x0;
	double x1;
	double y0;
	double y1;
	double diagram_a_x0;
	double diagram_a_x1;
	double diagram_a_y0;
	double diagram_a_y1;
	double diagram_b_x0;
	double diagram_b_x1;
	double diagram_b_y0;
	double diagram_b_y1;
	double diagram_c_x0;
	double diagram_c_x1;
	double diagram_c_y0;
	double diagram_c_y1;
	int colorMode; 
	int colorWrapping; 
	double maxValueAddition; 
	double hueShift;
	int settling; 
	int drawing; 
	double breatheRadius_c1c2; '''
	
	thelistofnames = legalKeyNames.replace(';','').split()
	for key in d:
		if key not in thelistofnames or key=='double' or key=='int':
			print 'Unknown parameter: ',key
			return False
	return True
	
	
	